site_name: CPPModelLibrary Documentation
repo_url: https://github.com/popwser/CPPModelLibrary/
repo_name: GitHub
edit_uri: ""
site_author: michaelbuerger

theme:
  name: "material"

markdown_extensions:
  - codehilite
  - admonition

extra:
  manifest: "manifest.webmanifest"

nav:
  - Documentation: index.md
